import {useMemo,useState} from 'react'
import {Copy,ExternalLink,Gamepad2,Globe2,Link2,Package,Plus,Sparkles,Star,Trash2,Users,MousePointerClick,Pencil,ToggleLeft,ToggleRight} from 'lucide-react'
import Modal from '../components/Modal'
import PageHeader from '../components/PageHeader'
import type {Touchpoint,TouchpointKind} from '../types'

type Props={touchpoints:Touchpoint[];addTouchpoint:(x:Omit<Touchpoint,'id'>)=>void;updateTouchpoint:(x:Touchpoint)=>void;deleteTouchpoint:(id:string)=>void}
const kinds:TouchpointKind[]=['Игра','Соцсеть','Taplink','Материал','Продукт','Ссылка']
const icons={Игра:Gamepad2,Соцсеть:Globe2,Taplink:Link2,Материал:Sparkles,Продукт:Package,Ссылка:Link2}
const empty:Omit<Touchpoint,'id'>={title:'',kind:'Ссылка',url:'',description:'',clicks:0,leads:0,active:true,pinned:false}

export default function Ecosystem({touchpoints,addTouchpoint,updateTouchpoint,deleteTouchpoint}:Props){
 const [filter,setFilter]=useState<'Все'|TouchpointKind>('Все');const [editing,setEditing]=useState<Touchpoint|null>(null);const [creating,setCreating]=useState(false);const [form,setForm]=useState<Omit<Touchpoint,'id'>>(empty);const [copied,setCopied]=useState<string|null>(null)
 const shown=useMemo(()=>touchpoints.filter(x=>filter==='Все'||x.kind===filter).sort((a,b)=>Number(b.pinned)-Number(a.pinned)),[touchpoints,filter])
 const totals=useMemo(()=>({clicks:touchpoints.reduce((a,x)=>a+x.clicks,0),leads:touchpoints.reduce((a,x)=>a+x.leads,0),active:touchpoints.filter(x=>x.active).length,conversion:touchpoints.reduce((a,x)=>a+x.clicks,0)?Math.round(touchpoints.reduce((a,x)=>a+x.leads,0)/touchpoints.reduce((a,x)=>a+x.clicks,0)*100):0}),[touchpoints])
 const openCreate=()=>{setForm(empty);setCreating(true)};const openEdit=(x:Touchpoint)=>{setEditing(x);setForm({...x})}
 const save=()=>{if(!form.title.trim()||!form.url.trim())return;if(editing)updateTouchpoint({...form,id:editing.id});else addTouchpoint(form);setEditing(null);setCreating(false)}
 const copy=async(x:Touchpoint)=>{await navigator.clipboard.writeText(x.url);setCopied(x.id);setTimeout(()=>setCopied(null),1400)}
 return <section className="screen ecosystem-screen"><PageHeader eyebrow="Creator OS" title="Касания" subtitle="Игры, площадки, Taplink, материалы и продукты — в одном центре управления." action={<button className="primary" onClick={openCreate}><Plus size={18}/>Добавить</button>}/>
 <div className="touch-metrics"><article><MousePointerClick/><span>Переходы</span><strong>{totals.clicks}</strong></article><article><Users/><span>Заявки</span><strong>{totals.leads}</strong></article><article><Sparkles/><span>Конверсия</span><strong>{totals.conversion}%</strong></article><article><ToggleRight/><span>Активно</span><strong>{totals.active}</strong></article></div>
 <div className="touch-tabs"><button className={filter==='Все'?'active':''} onClick={()=>setFilter('Все')}>Все</button>{kinds.map(k=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}>{k}</button>)}</div>
 <div className="touch-grid">{shown.map(x=>{const Icon=icons[x.kind];return <article className={`touch-card ${!x.active?'disabled':''}`} key={x.id}><div className="touch-card-top"><div className="touch-icon"><Icon/></div><div className="grow"><div className="touch-title"><h3>{x.title}</h3>{x.pinned&&<Star size={15} fill="currentColor"/>}</div><span className="touch-kind">{x.kind}</span></div><button className="icon-btn" onClick={()=>openEdit(x)}><Pencil size={17}/></button></div><p>{x.description||'Без описания'}</p><div className="touch-stats"><span><MousePointerClick size={15}/>{x.clicks}</span><span><Users size={15}/>{x.leads}</span><b>{x.clicks?Math.round(x.leads/x.clicks*100):0}%</b></div><div className="touch-actions"><a className="secondary" href={x.url} target="_blank" rel="noreferrer"><ExternalLink size={16}/>Открыть</a><button className="secondary" onClick={()=>copy(x)}><Copy size={16}/>{copied===x.id?'Скопировано':'Копировать'}</button></div></article>})}</div>
 {(creating||editing)&&<Modal title={editing?'Редактировать касание':'Новое касание'} onClose={()=>{setCreating(false);setEditing(null)}}><div className="touch-form"><label>Название<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Например, English Escape"/></label><div className="form-row"><label>Тип<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as TouchpointKind})}>{kinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Ссылка<input value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://"/></label></div><label>Описание<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-row"><label>Переходы<input type="number" min="0" value={form.clicks} onChange={e=>setForm({...form,clicks:Number(e.target.value)})}/></label><label>Заявки<input type="number" min="0" value={form.leads} onChange={e=>setForm({...form,leads:Number(e.target.value)})}/></label></div><div className="touch-switches"><button type="button" onClick={()=>setForm({...form,active:!form.active})}>{form.active?<ToggleRight/>:<ToggleLeft/>} Активно</button><button type="button" onClick={()=>setForm({...form,pinned:!form.pinned})}><Star fill={form.pinned?'currentColor':'none'}/> Закрепить</button></div><div className="modal-actions">{editing&&<button className="danger-btn" onClick={()=>{deleteTouchpoint(editing.id);setEditing(null)}}><Trash2 size={17}/>Удалить</button>}<button className="secondary" onClick={()=>{setCreating(false);setEditing(null)}}>Отмена</button><button className="primary" onClick={save}>Сохранить</button></div></div></Modal>}
 </section>
}
