import {useEffect,useMemo,useState} from 'react'
import type {ContentItem,Lead,LeadStatus,Lesson,Material,Student,Task,Touchpoint} from '../types'
const localDate=()=>{const d=new Date();const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
const today=localDate()
const studentsSeed:Student[]=[
{id:'s1',name:'Анна Смирнова',level:'B1',goal:'Уверенно говорить на работе',phone:'+7 900 111-22-33',telegram:'@anna_s',rate:1800,balance:3600,status:'Активный',timezone:'Москва',interests:'Кино, работа, путешествия',strengths:'Хорошо понимает речь на слух',challenges:'Путает времена в спонтанной речи',note:'Любит практичные темы и короткие домашние задания.',packageTotal:12,packageUsed:8},
{id:'s2',name:'Мария Иванова',level:'B2',goal:'Свободнее обсуждать сложные темы',phone:'+7 900 222-33-44',telegram:'@maria_i',rate:2000,balance:2000,status:'Активный',timezone:'Москва',interests:'Книги, статьи, психология',strengths:'Большой словарный запас',challenges:'Хочет звучать естественнее',note:'Лучше всего вовлекается через статьи и подкасты.',packageTotal:8,packageUsed:5},
{id:'s3',name:'Иван Петров',level:'A2',goal:'Систематизировать грамматику',phone:'+7 900 333-44-55',telegram:'@ivan_p',rate:1700,balance:-1700,status:'Активный',timezone:'Москва',interests:'Технологии, спорт',strengths:'Регулярно занимается',challenges:'Боится ошибаться',note:'Нужны понятные схемы и повторение.',packageTotal:10,packageUsed:9}]
const leadsSeed:Lead[]=[
{id:'l1',name:'Екатерина',source:'Threads',contact:'@katya',createdAt:'Сегодня, 09:21',status:'Новая',goal:'Английский для путешествий',note:'Готова начать в августе'},
{id:'l2',name:'Ольга',source:'Telegram',contact:'@olga',createdAt:'Вчера, 18:40',status:'Пробный урок',goal:'Перейти с A2 на B1',note:'Пробный в четверг'},
{id:'l3',name:'Алексей',source:'Instagram',contact:'@alex',createdAt:'26 июля',status:'Связались',goal:'Английский для работы',note:'Ждёт варианты времени'}]
const lessonsSeed:Lesson[]=[
{id:'e1',studentId:'s1',student:'Анна Смирнова',date:today,time:'10:00',duration:60,topic:'Speaking: work routines',status:'Запланирован',paid:true,homework:'Подготовить 5 вопросов коллеге',plan:'Разминка → статья → ролевой диалог → обратная связь',notes:'',errors:'Present Perfect vs Past Simple',mood:'Спокойное'},
{id:'e2',studentId:'s2',student:'Мария Иванова',date:today,time:'12:00',duration:60,topic:'Article discussion',status:'Запланирован',paid:true,homework:'Прочитать статью и выписать 7 выражений',plan:'Обсудить заголовок, лексику, аргументы автора',notes:'',errors:'Natural collocations',mood:'Отличное'},
{id:'e3',student:'Пробное занятие',date:today,time:'18:00',duration:45,topic:'Диагностика',status:'Запланирован',paid:false,homework:'',plan:'Цели → speaking → grammar → план на 3 месяца',notes:'',errors:'',mood:'Спокойное'},
{id:'e4',studentId:'s3',student:'Иван Петров',date:'2026-07-29',time:'18:00',duration:60,topic:'Past Simple vs Present Perfect',status:'Запланирован',paid:false,homework:'Упражнения 1–3',plan:'Повторение правила → контролируемая практика → речь',notes:'',errors:'Irregular verbs',mood:'Сложно'},
{id:'e5',studentId:'s1',student:'Анна Смирнова',date:'2026-07-24',time:'10:00',duration:60,topic:'Meetings and small talk',status:'Проведён',paid:true,homework:'Записать голосовое',plan:'',notes:'Хорошо использовала новую лексику.',errors:'Articles with jobs',mood:'Отличное'}]
const tasksSeed:Task[]=[{id:'t1',title:'Проверить домашнее Анны',due:'Сегодня',done:false,category:'Домашнее'},{id:'t2',title:'Ответить Екатерине',due:'Сегодня',done:false,category:'Заявка'},{id:'t3',title:'Напомнить Ивану об оплате',due:'Сегодня',done:false,category:'Оплата'}]

const touchpointsSeed:Touchpoint[]=[
{id:'tp1',title:'English Escape',kind:'Игра',url:'https://example.com/english-escape',description:'Интерактивная игра для разговорной практики и повторения лексики.',clicks:126,leads:8,active:true,pinned:true},
{id:'tp2',title:'Telegram-канал',kind:'Соцсеть',url:'https://t.me/',description:'Основной канал с разборами английского, книг и современной лексики.',clicks:248,leads:14,active:true,pinned:true},
{id:'tp3',title:'Threads',kind:'Соцсеть',url:'https://threads.net/',description:'Короткие заметки о преподавании, языке и рабочих наблюдениях.',clicks:181,leads:11,active:true,pinned:false},
{id:'tp4',title:'Taplink',kind:'Taplink',url:'https://taplink.cc/',description:'Главная страница со ссылками, квизом и записью на занятие.',clicks:94,leads:9,active:true,pinned:true},
{id:'tp5',title:'Гайд для взрослых учеников',kind:'Материал',url:'https://example.com/guide',description:'Бесплатный материал после прохождения диагностики.',clicks:73,leads:5,active:true,pinned:false}
]

const contentSeed:ContentItem[]=[
{id:'c1',title:'Почему взрослые знают правила, но не говорят',platform:'Threads',stage:'Черновик',deadline:today,tags:['speaking','взрослые'],note:'Начать с истории ученика и закончить мягким приглашением на диагностику.'},
{id:'c2',title:'Разбор летней лексики из сериала',platform:'Telegram',stage:'Идея',deadline:'',tags:['лексика','лето'],note:'5 выражений + маленькое задание в комментариях.'},
{id:'c3',title:'Как проходят мои занятия',platform:'Instagram',stage:'Готов',deadline:today,tags:['уроки','обо мне'],note:'Карусель на 7 слайдов, добавить скриншоты материалов.'},
{id:'c4',title:'Книжный клуб как игра',platform:'Threads',stage:'Опубликован',deadline:'',tags:['книги','клуб'],note:''}
]

const materialsSeed:Material[]=[{id:'m1',studentId:'s1',title:'Useful phrases for meetings',kind:'Рабочий лист',url:'#'},{id:'m2',studentId:'s1',title:'How to make small talk',kind:'Статья',url:'#'},{id:'m3',studentId:'s2',title:'The psychology of habits',kind:'Статья',url:'#'}]
function read<T>(k:string,f:T):T{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}
export function useWorkspace(){
 const [contentItems,setContentItems]=useState(()=>read('ira.v3.content',contentSeed));const [touchpoints,setTouchpoints]=useState(()=>read('ira.v3.touchpoints',touchpointsSeed));const [students,setStudents]=useState(()=>read('ira.v2.students',studentsSeed));const [leads,setLeads]=useState(()=>read('ira.v2.leads',leadsSeed));const [lessons,setLessons]=useState(()=>read('ira.v2.lessons',lessonsSeed));const [tasks,setTasks]=useState(()=>read('ira.v2.tasks',tasksSeed));const [materials,setMaterials]=useState(()=>read('ira.v2.materials',materialsSeed));const [dark,setDark]=useState(()=>read('ira.v2.dark',false))
 useEffect(()=>localStorage.setItem('ira.v3.content',JSON.stringify(contentItems)),[contentItems]);useEffect(()=>localStorage.setItem('ira.v3.touchpoints',JSON.stringify(touchpoints)),[touchpoints]);useEffect(()=>localStorage.setItem('ira.v2.students',JSON.stringify(students)),[students]);useEffect(()=>localStorage.setItem('ira.v2.leads',JSON.stringify(leads)),[leads]);useEffect(()=>localStorage.setItem('ira.v2.lessons',JSON.stringify(lessons)),[lessons]);useEffect(()=>localStorage.setItem('ira.v2.tasks',JSON.stringify(tasks)),[tasks]);useEffect(()=>localStorage.setItem('ira.v2.materials',JSON.stringify(materials)),[materials]);useEffect(()=>{localStorage.setItem('ira.v2.dark',JSON.stringify(dark));document.documentElement.dataset.theme=dark?'dark':'light'},[dark])
 const stats=useMemo(()=>({activeStudents:students.filter(s=>s.status==='Активный').length,activeLeads:leads.filter(l=>!['Стала ученицей','Отказ'].includes(l.status)).length,todayLessons:lessons.filter(l=>l.date===today&&l.status!=='Отменён').length,revenue:lessons.filter(l=>l.paid&&l.status==='Проведён').reduce((a,l)=>a+(students.find(s=>s.id===l.studentId)?.rate||0),0),debt:students.filter(s=>s.balance<0).reduce((a,s)=>a+Math.abs(s.balance),0),conversion:leads.length?Math.round(leads.filter(l=>l.status==='Стала ученицей').length/leads.length*100):0}),[students,leads,lessons])
 const insights=useMemo(()=>{const out:string[]=[];const low=students.filter(s=>s.packageTotal-s.packageUsed<=2&&s.status==='Активный');if(low.length)out.push(`У ${low[0].name.split(' ')[0]} осталось ${low[0].packageTotal-low[0].packageUsed} занятия в пакете.`);const debt=students.find(s=>s.balance<0);if(debt)out.push(`${debt.name.split(' ')[0]}: нужно напомнить об оплате ${Math.abs(debt.balance).toLocaleString('ru-RU')} ₽.`);const fresh=leads.find(l=>l.status==='Новая');if(fresh)out.push(`Новая заявка от ${fresh.name} из ${fresh.source}.`);return out},[students,leads])
 return {students,leads,lessons,tasks,materials,touchpoints,contentItems,dark,setDark,stats,insights,
 addStudent:(x:Omit<Student,'id'>)=>setStudents(v=>[{...x,id:crypto.randomUUID()},...v]),updateStudent:(x:Student)=>setStudents(v=>v.map(s=>s.id===x.id?x:s)),deleteStudent:(id:string)=>setStudents(v=>v.filter(s=>s.id!==id)),
 addLead:(x:Omit<Lead,'id'|'createdAt'|'status'>)=>setLeads(v=>[{...x,id:crypto.randomUUID(),createdAt:'Только что',status:'Новая'},...v]),updateLeadStatus:(id:string,status:LeadStatus)=>setLeads(v=>v.map(l=>l.id===id?{...l,status}:l)),deleteLead:(id:string)=>setLeads(v=>v.filter(l=>l.id!==id)),
 addLesson:(x:Omit<Lesson,'id'>)=>setLessons(v=>[...v,{...x,id:crypto.randomUUID()}]),updateLesson:(x:Lesson)=>setLessons(v=>v.map(l=>l.id===x.id?x:l)),deleteLesson:(id:string)=>setLessons(v=>v.filter(l=>l.id!==id)),
 addTask:(title:string)=>setTasks(v=>[{id:crypto.randomUUID(),title,due:'Сегодня',done:false,category:'Другое'},...v]),toggleTask:(id:string)=>setTasks(v=>v.map(t=>t.id===id?{...t,done:!t.done}:t)),deleteTask:(id:string)=>setTasks(v=>v.filter(t=>t.id!==id)),
 addContentItem:(x:Omit<ContentItem,'id'>)=>setContentItems(v=>[{...x,id:crypto.randomUUID()},...v]),updateContentItem:(x:ContentItem)=>setContentItems(v=>v.map(c=>c.id===x.id?x:c)),deleteContentItem:(id:string)=>setContentItems(v=>v.filter(c=>c.id!==id)),
 addTouchpoint:(x:Omit<Touchpoint,'id'>)=>setTouchpoints(v=>[{...x,id:crypto.randomUUID()},...v]),updateTouchpoint:(x:Touchpoint)=>setTouchpoints(v=>v.map(t=>t.id===x.id?x:t)),deleteTouchpoint:(id:string)=>setTouchpoints(v=>v.filter(t=>t.id!==id)),
 addMaterial:(x:Omit<Material,'id'>)=>setMaterials(v=>[{...x,id:crypto.randomUUID()},...v]),deleteMaterial:(id:string)=>setMaterials(v=>v.filter(m=>m.id!==id)),
 exportData:()=>JSON.stringify({students,leads,lessons,tasks,materials,touchpoints,contentItems},null,2),importData:(raw:string)=>{const x=JSON.parse(raw);if(x.students)setStudents(x.students);if(x.leads)setLeads(x.leads);if(x.lessons)setLessons(x.lessons);if(x.tasks)setTasks(x.tasks);if(x.materials)setMaterials(x.materials);if(x.touchpoints)setTouchpoints(x.touchpoints);if(x.contentItems)setContentItems(x.contentItems)},reset:()=>{Object.keys(localStorage).filter(k=>k.startsWith('ira.v2')||k.startsWith('ira.v3')).forEach(k=>localStorage.removeItem(k));location.reload()}}
}
