import assert from "node:assert/strict";
import test from "node:test";

import {
  applyAutomaticReports,
  singleLessonDebt,
  studentPaymentDebt,
} from "../backend/supabase/functions/_shared/workspace-automation.ts";

const minute = 60_000;
const lessonEndMs = (lesson) => Date.parse(`${lesson.date}T${lesson.time}:00Z`) + Number(lesson.duration ?? 60) * minute;

function baseState() {
  return {
    automationSettings: { autoReports: true, autoReportAfterHours: 24, autoReportLookbackDays: 60 },
    students: [{
      id: "student-1",
      name: "Юлия",
      paymentMode: "package",
      lessonPrice: 1_000,
      packageTotal: 8,
      packageUsed: 2,
      packagePrice: 8_000,
      packagePaid: 8_000,
      autoDeduct: true,
    }],
    lessons: [
      { id: "lesson-due", studentId: "student-1", date: "2026-08-13", time: "09:00", duration: 60, status: "planned", paymentType: "package" },
      { id: "lesson-cancelled", studentId: "student-1", date: "2026-08-13", time: "10:00", duration: 60, status: "cancelled", paymentType: "package" },
      { id: "lesson-too-old", studentId: "student-1", date: "2026-05-01", time: "10:00", duration: 60, status: "planned", paymentType: "package" },
    ],
  };
}

test("forms a report after 24 hours, skips cancelled and old lessons, and is idempotent", () => {
  const nowMs = Date.parse("2026-08-15T12:00:00Z");
  const first = applyAutomaticReports(baseState(), { nowMs, lessonEndMs });
  assert.equal(first.reports.length, 1);
  assert.equal(first.skippedOlderLessons, 1);
  assert.equal(first.state.students[0].packageUsed, 3);

  const due = first.state.lessons.find((lesson) => lesson.id === "lesson-due");
  assert.equal(due.status, "completed");
  assert.equal(due.reportCompleted, true);
  assert.equal(due.autoReportGenerated, true);
  assert.equal(due.report.autoGenerated, true);
  assert.equal(due.packageCounted, true);
  assert.equal(due.paymentReview, "");
  assert.equal(first.state.lessons.find((lesson) => lesson.id === "lesson-cancelled").status, "cancelled");
  assert.equal(first.state.lessons.find((lesson) => lesson.id === "lesson-too-old").status, "planned");

  const second = applyAutomaticReports(first.state, { nowMs: nowMs + minute, lessonEndMs });
  assert.equal(second.reports.length, 0);
  assert.equal(second.state.students[0].packageUsed, 3);
});

test("flags package accounting for review when the package is exhausted", () => {
  const state = baseState();
  state.students[0].packageUsed = state.students[0].packageTotal;
  state.lessons = [state.lessons[0]];
  const result = applyAutomaticReports(state, { nowMs: Date.parse("2026-08-15T12:00:00Z"), lessonEndMs });
  assert.equal(result.reports.length, 1);
  assert.equal(result.state.students[0].packageUsed, 8);
  assert.equal(result.state.lessons[0].packageCounted, false);
  assert.equal(result.state.lessons[0].paymentReview, "package_exhausted");
});

test("respects the auto-report and package auto-deduction switches", () => {
  const disabled = baseState();
  disabled.automationSettings.autoReports = false;
  const untouched = applyAutomaticReports(disabled, { nowMs: Date.parse("2026-08-15T12:00:00Z"), lessonEndMs });
  assert.equal(untouched.reports.length, 0);
  assert.equal(untouched.state.lessons[0].status, "planned");

  const manualDeduction = baseState();
  manualDeduction.students[0].autoDeduct = false;
  manualDeduction.lessons = [manualDeduction.lessons[0]];
  const result = applyAutomaticReports(manualDeduction, { nowMs: Date.parse("2026-08-15T12:00:00Z"), lessonEndMs });
  assert.equal(result.state.students[0].packageUsed, 2);
  assert.equal(result.state.lessons[0].paymentReview, "auto_deduct_off");
});

test("payment debt includes unpaid one-off lessons even for a package student", () => {
  const state = {
    students: [],
    lessons: [
      { id: "one", studentId: "student-1", status: "completed", paymentType: "single", paid: false },
      { id: "two", studentId: "student-1", status: "completed", paymentType: "single", paid: true },
      { id: "three", studentId: "student-1", status: "cancelled", paymentType: "single", paid: false },
    ],
  };
  const packageStudent = { id: "student-1", paymentMode: "package", lessonPrice: 1_000, packagePrice: 8_000, packagePaid: 7_500 };
  assert.equal(singleLessonDebt(state, packageStudent), 1_000);
  assert.equal(studentPaymentDebt(state, packageStudent), 1_500);

  const singleStudent = { ...packageStudent, paymentMode: "single" };
  assert.equal(studentPaymentDebt(state, singleStudent), 1_000);
});
