import {useMemo,useState} from 'react'
import {CalendarDays,GripVertical,Instagram,MessageCircle,Plus,Send,Trash2} from 'lucide-react'
import Modal from '../components/Modal'
import PageHeader from '../components/PageHeader'
import type {ContentItem,ContentStage,ContentPlatform} from '../types'

type Props={contentItems:ContentItem[];addContentItem:(x:Omit<ContentItem,'id'>)=>void;updateContentItem:(x:ContentItem)=>void;deleteContentItem:(id:string)=>void}
const stages:ContentStage[]=['Идея','Черновик','Готов','Опубликован']
const platforms:ContentPlatform[]=['Threads','Telegram','Instagram']
const stageLabel:Record<ContentStage,string>={Идея:'Идеи',Черновик:'В работе',Готов:'Готово',Опубликован:'Опубликовано'}
const empty:Omit<ContentItem,'id'>={title:'',platform:'Threads',stage:'Идея',deadline:'',tags:[],note:''}
const PlatformIcon=({platform}:{platform:ContentPlatform})=>platform==='Instagram'?<Instagram size={15}/>:platform==='Telegram'?<Send size={15}/>:<MessageCircle size={15}/>

export default function Content({contentItems,addContentItem,updateContentItem,deleteContentItem}:Props){
 const [creating,setCreating]=useState(false);const [editing,setEditing]=useState<ContentItem|null>(null);const [form,setForm]=useState<Omit<ContentItem,'id'>>(empty)
 const grouped=useMemo(()=>Object.fromEntries(stages.map(stage=>[stage,contentItems.filter(x=>x.stage===stage)])) as Record<ContentStage,ContentItem[]>,[contentItems])
 const openCreate=(stage:ContentStage='Идея')=>{setEditing(null);setForm({...empty,stage});setCreating(true)}
 const openEdit=(item:ContentItem)=>{setEditing(item);setForm({...item})}
 const save=()=>{if(!form.title.trim())return;if(editing)updateContentItem({...form,id:editing.id});else addContentItem(form);setCreating(false);setEditing(null)}
 const move=(item:ContentItem,direction:1|-1)=>{const i=stages.indexOf(item.stage);const next=stages[i+direction];if(next)updateContentItem({...item,stage:next})}
 return <section className="screen content-screen"><PageHeader eyebrow="Creator OS" title="Контент" subtitle="От идеи до публикации — без потерянных заметок и десятка разных приложений." action={<button className="primary" onClick={()=>openCreate()}><Plus size={18}/>Новая идея</button>}/>
 <div className="content-summary"><article><strong>{contentItems.length}</strong><span>всего материалов</span></article><article><strong>{grouped['Черновик'].length}</strong><span>сейчас в работе</span></article><article><strong>{grouped['Готов'].length}</strong><span>готовы к публикации</span></article></div>
 <div className="kanban-board">{stages.map(stage=><section className="kanban-column" key={stage}><header><div><span className={`stage-dot stage-${stage}`}/><h2>{stageLabel[stage]}</h2><b>{grouped[stage].length}</b></div><button className="icon-btn" onClick={()=>openCreate(stage)}><Plus size={17}/></button></header><div className="kanban-list">{grouped[stage].map(item=><article className="content-card" key={item.id} onClick={()=>openEdit(item)}><div className="content-card-top"><span className="drag"><GripVertical size={16}/></span><span className={`platform platform-${item.platform}`}><PlatformIcon platform={item.platform}/>{item.platform}</span></div><h3>{item.title}</h3>{item.note&&<p>{item.note}</p>}<div className="tag-row">{item.tags.map(t=><span key={t}>#{t}</span>)}</div><footer>{item.deadline?<span><CalendarDays size={14}/>{new Date(`${item.deadline}T12:00:00`).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</span>:<span>Без дедлайна</span>}<div>{stage!=='Идея'&&<button onClick={e=>{e.stopPropagation();move(item,-1)}}>←</button>}{stage!=='Опубликован'&&<button onClick={e=>{e.stopPropagation();move(item,1)}}>→</button>}</div></footer></article>)}{!grouped[stage].length&&<button className="empty-column" onClick={()=>openCreate(stage)}><Plus size={18}/>Добавить карточку</button>}</div></section>)}</div>
 {(creating||editing)&&<Modal title={editing?'Редактировать материал':'Новый материал'} onClose={()=>{setCreating(false);setEditing(null)}}><div className="touch-form"><label>Название<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="О чём будет пост?"/></label><div className="form-row"><label>Площадка<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value as ContentPlatform})}>{platforms.map(x=><option key={x}>{x}</option>)}</select></label><label>Этап<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value as ContentStage})}>{stages.map(x=><option key={x}>{stageLabel[x]}</option>)}</select></label></div><label>Дедлайн<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label><label>Теги<input value={form.tags.join(', ')} onChange={e=>setForm({...form,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} placeholder="лексика, книги, продажи"/></label><label>Заметка<textarea rows={4} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Ключевая мысль, структура или призыв..."/></label><div className="modal-actions">{editing&&<button className="danger-btn" onClick={()=>{deleteContentItem(editing.id);setEditing(null)}}><Trash2 size={17}/>Удалить</button>}<button className="secondary" onClick={()=>{setCreating(false);setEditing(null)}}>Отмена</button><button className="primary" onClick={save}>Сохранить</button></div></div></Modal>}
 </section>
}
