export type AutomaticReport = {
  lessonId: string;
  studentId: string;
  studentName: string;
  packageCounted: boolean;
  paymentReview: "" | "package_exhausted" | "auto_deduct_off";
};

export type AutomaticReportResult = {
  state: any;
  reports: AutomaticReport[];
  skippedOlderLessons: number;
};

function boundedNumber(value: unknown, fallback: number, minimum: number, maximum: number) {
  const number = Number(value);
  return Number.isFinite(number) ? Math.min(maximum, Math.max(minimum, number)) : fallback;
}

export function automaticReportConfig(state: any) {
  const settings = state?.automationSettings ?? {};
  return {
    enabled: settings.autoReports !== false,
    afterHours: boundedNumber(settings.autoReportAfterHours, 24, 1, 168),
    lookbackDays: boundedNumber(settings.autoReportLookbackDays, 60, 1, 365),
  };
}

export function lessonPaymentType(lesson: any, student: any): "single" | "package" {
  if (lesson?.paymentType === "single" || lesson?.paymentType === "package") return lesson.paymentType;
  return student?.paymentMode === "single" ? "single" : "package";
}

export function singleLessonDebt(state: any, student: any) {
  const unpaid = (Array.isArray(state?.lessons) ? state.lessons : []).filter((lesson: any) =>
    String(lesson.studentId) === String(student.id) &&
    lesson.status === "completed" &&
    lessonPaymentType(lesson, student) === "single" &&
    !lesson.paid
  ).length;
  return unpaid * Math.max(0, Number(student.lessonPrice ?? 0));
}

export function studentPaymentDebt(state: any, student: any) {
  const packageDebt = student?.paymentMode === "single"
    ? 0
    : Math.max(0, Number(student?.packagePrice ?? 0) - Number(student?.packagePaid ?? 0));
  return packageDebt + singleLessonDebt(state, student);
}

export function applyAutomaticReports(
  currentState: any,
  options: { nowMs?: number; lessonEndMs: (lesson: any) => number },
): AutomaticReportResult {
  const config = automaticReportConfig(currentState);
  if (!config.enabled) return { state: currentState, reports: [], skippedOlderLessons: 0 };

  const nowMs = Number.isFinite(options.nowMs) ? Number(options.nowMs) : Date.now();
  const nextState = structuredClone(currentState ?? {});
  const lessons = Array.isArray(nextState.lessons) ? nextState.lessons : [];
  const students = Array.isArray(nextState.students) ? nextState.students : [];
  const studentsById = new Map(students.map((student: any) => [String(student.id), student]));
  const reports: AutomaticReport[] = [];
  let skippedOlderLessons = 0;

  for (const lesson of lessons) {
    if (lesson?.status !== "planned" || !lesson?.id || !lesson?.studentId) continue;
    const endMs = Number(options.lessonEndMs(lesson));
    if (!Number.isFinite(endMs)) continue;
    const ageMs = nowMs - endMs;
    if (ageMs < config.afterHours * 60 * 60_000) continue;
    if (ageMs > config.lookbackDays * 24 * 60 * 60_000) {
      skippedOlderLessons++;
      continue;
    }

    const student = studentsById.get(String(lesson.studentId)) as any;
    if (!student) continue;
    const generatedAt = new Date(nowMs).toISOString();
    const oldReport = lesson.report && typeof lesson.report === "object" ? lesson.report : {};
    const paymentType = lessonPaymentType(lesson, student);
    let packageCounted = Boolean(lesson.packageCounted);
    let paymentReview: AutomaticReport["paymentReview"] = "";

    if (paymentType === "package") {
      const total = Math.max(0, Number(student.packageTotal ?? 0));
      const used = Math.max(0, Number(student.packageUsed ?? 0));
      if (student.autoDeduct === false) {
        packageCounted = false;
        paymentReview = "auto_deduct_off";
      } else if (!packageCounted && total > 0 && used < total) {
        student.packageUsed = Math.min(total, used + 1);
        packageCounted = true;
      } else if (!packageCounted) {
        paymentReview = "package_exhausted";
      }
    } else {
      packageCounted = false;
    }

    lesson.status = "completed";
    lesson.reportCompleted = true;
    lesson.completedAt = generatedAt;
    lesson.autoReportGenerated = true;
    lesson.autoReportGeneratedAt = generatedAt;
    lesson.accountingVersion = 1;
    lesson.packageCounted = packageCounted;
    lesson.paymentReview = paymentReview;
    lesson.report = {
      summary: String(oldReport.summary || "Урок отмечен автоматически: в Rasmus не было отмены в течение 24 часов."),
      progress: String(oldReport.progress || "Добавьте результаты занятия, если хотите сохранить подробности."),
      homework: String(oldReport.homework || ""),
      updatedAt: generatedAt,
      autoGenerated: true,
      autoGeneratedAt: generatedAt,
    };

    reports.push({
      lessonId: String(lesson.id),
      studentId: String(student.id),
      studentName: String(student.name || "Ученик"),
      packageCounted,
      paymentReview,
    });
  }

  if (reports.length) {
    nextState.automationSettings = {
      ...(nextState.automationSettings ?? {}),
      autoReports: true,
      autoReportAfterHours: config.afterHours,
      autoReportLookbackDays: config.lookbackDays,
      lastAutoReportAt: new Date(nowMs).toISOString(),
    };
  }
  return { state: nextState, reports, skippedOlderLessons };
}
